In [105]:
import numpy as np

def Convolution2D(matrix, fltr, stride=1, padding=0):
    filter_height, filter_width = fltr.shape
    result_height = ((matrix.shape[0] + 2 * padding - filter_height) // stride) + 1
    result_width = ((matrix.shape[1] + 2 * padding - filter_width) // stride) + 1

    padded_matrix = np.pad(matrix, padding, mode='constant')
    result = np.zeros((result_height, result_width))

    for i in range(result_height):
        for j in range(result_width):
            result[i, j] = np.sum(
                padded_matrix[
                    i*stride:i*stride+filter_height,
                    j*stride:j*stride+filter_width
                ] * fltr
            )
            
    return result

In [106]:
from torch.nn.functional import conv2d
from torch import from_numpy
import torch

for s in range(1, 4):
    for p in range(0, 4):
        for i in range(3, 11):
            data = np.round(np.random.rand(i, i), 3)
            kernel = np.round(np.random.rand(3,3), 3)

            res_matrix = Convolution2D(data, kernel, padding=p, stride=s)
            torch_matrix = conv2d(
                from_numpy(data).reshape(1, 1, i, i),
                from_numpy(kernel).reshape(1, 1, 3, 3),
                padding=p,
                stride=s)
            
            res_matrix = np.round(res_matrix, 3)
            torch_matrix = torch.round(torch_matrix[0][0], decimals=3).numpy()
            
            print('Stride:', s)
            print('Padding:', j)
            print('Входящая матрица', data.shape ,':\n', data, '\n')
            print('Ядро', kernel.shape,':\n', kernel, '\n')
            print('Результирующая матрица', res_matrix.shape ,':\n', res_matrix, '\n')
            print('Результирующая матрица torch', torch_matrix.shape ,':\n', torch_matrix, '\n')

            print('Cравниваем результат с torch conv2d:')
            assert (res_matrix == torch_matrix).all()
            print('Успех!', '\n\n')


Stride: 1
Padding: 0
Входящая матрица (3, 3) :
 [[0.433 0.047 0.635]
 [0.94  0.333 0.634]
 [0.143 0.427 0.661]] 

Ядро (3, 3) :
 [[0.177 0.122 0.306]
 [0.112 0.637 0.915]
 [0.227 0.931 0.308]] 

Результирующая матрица (1, 1) :
 [[1.808]] 

Результирующая матрица torch (1, 1) :
 [[1.808]] 

Cравниваем результат с torch conv2d:
Успех! 


Stride: 1
Padding: 0
Входящая матрица (4, 4) :
 [[0.836 0.443 0.671 0.243]
 [0.686 0.564 0.89  0.473]
 [0.792 0.97  0.905 0.1  ]
 [0.189 0.23  0.582 0.18 ]] 

Ядро (3, 3) :
 [[0.021 0.797 0.485]
 [0.067 0.055 0.822]
 [0.05  0.682 0.097]] 

Результирующая матрица (2, 2) :
 [[2.294 1.813]
 [1.969 1.573]] 

Результирующая матрица torch (2, 2) :
 [[2.294 1.813]
 [1.969 1.573]] 

Cравниваем результат с torch conv2d:
Успех! 


Stride: 1
Padding: 0
Входящая матрица (5, 5) :
 [[0.856 0.075 0.338 0.327 0.899]
 [0.533 0.225 0.41  0.409 0.146]
 [0.282 0.397 0.893 0.594 0.796]
 [0.821 0.295 0.769 0.783 0.394]
 [0.364 0.676 0.482 0.326 0.837]] 

Ядро (3, 3) :
 [[0.71